# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build physics-driven-ml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  # Cancels jobs running if new commits are pushed
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: firedrakeproject/firedrake-vanilla:latest
      options: --user root
    steps:
    - uses: actions/checkout@v2
    - name: Check out branches
      shell: bash -l {0}
      run: |
        git config --global --add safe.directory /home/firedrake/firedrake/src/firedrake
        cd /home/firedrake/firedrake/src/firedrake
        git checkout pytorch_coupling
        git config --global --add safe.directory /home/firedrake/firedrake/src/pyadjoint
        cd /home/firedrake/firedrake/src/pyadjoint
        git checkout adjoint-1-forms
    - name: Install torch
      shell: bash -l {0}
      run: |
        source /home/firedrake/firedrake/bin/activate
        python -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        source /home/firedrake/firedrake/bin/activate
        python -m pip install --upgrade pip
        python -m pip install pytest
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        source /home/firedrake/firedrake/bin/activate
        python -m pytest ./tests/
